### ISSUE TITLE
date column's data should never wrap

### ISSUE THREAD

**Issue by NovemLinguae** [APerson241/afchistory#24]
Requested by KylieTastic at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFC_history_tool

Very long draft/article names will cause the date column to wrap on _**Edge and Chrome, not Firefox**_.

Changing the CSS to `table-layout: fixed` and then setting `width: X%` for each column should do the trick.

Pick a width that never wraps the last two columns.

![image](https://github.com/enterprisey/afchistory/assets/79697282/e6fb3f66-256b-4bbe-81ea-da752b382c6e)

**Comment by TimWardC3** [comment]
Thanks :)
