### ISSUE TITLE
Same drafts listed ~50 times

### ISSUE THREAD

**Issue by josve05a** [APerson241/afchistory#3]
Screenshot on Google Drive (7-8 Megeapixles):  https://drive.google.com/a/utb.nacka.se/file/d/0B9BuJYqrg4ldSnVUTUUzQk1EazQ/view?usp=sharing
![afc review history](https://cloud.githubusercontent.com/assets/7117013/8534630/6f99b7b4-243e-11e5-83d3-a0fe44a43446.png)

**Comment by josve05a** [comment]
I've marked my edits to Colby Keller in yellow here. I made 2 edits, listed 110 times. On a Chromebook ChromeOS: Mozilla/5.0 (X11; CrOS x86_64 6946.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by enterprisey** [comment]
Fixed with 433cf05.
